apiVersion: batch/v1
kind: Job
metadata:
  name: train-ml-k8s
spec:
  template:
    spec:
      containers:
      - name: train-ml-k8s
        imagePullPolicy: Always
        image: loup21991/train-sklearn:0.1
        command: ["python3",  "test/train.py"]
      restartPolicy: Never
  backoffLimit: 0